# task 1 biodata 
nama = input("Nama Lengkap: ")
nim = input("Nim: ")
ttl = input("Tempat Tanggal Lahir: ")
alamat = input("Alamat: ")
no = input("No. Hp: ")
jurusan = input("Program Study: ")
suka = input("Hobi: ")

print("Biodata Diri")
print("Nama Lengkap : " + nama)
print("Nim          : " + nim)
print("TTL          : " + ttl)
print("Alamat       : " + alamat)
print("No Hp        : " + no)
print("Prodi        : " + jurusan)
print("Hoby         : " + suka)